import ReactPDF from '@react-pdf/renderer';
import React from 'react';
import type { FormDef } from '@itatti/shared';

const { Document, Page, Text, View, StyleSheet } = ReactPDF;

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  title: { fontSize: 18, marginBottom: 20, fontFamily: 'Helvetica-Bold' },
  sectionTitle: { fontSize: 14, marginTop: 16, marginBottom: 8, fontFamily: 'Helvetica-Bold' },
  fieldRow: { marginBottom: 6 },
  fieldLabel: { fontSize: 9, color: '#666', marginBottom: 2 },
  fieldValue: { fontSize: 11 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' },
});

function FormDocument({ formDef, data }: { formDef: FormDef; data: Record<string, unknown> }) {
  return React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      React.createElement(Text, { style: styles.title }, formDef.title),
      ...formDef.sections.map((section, si) =>
        React.createElement(View, { key: si },
          React.createElement(Text, { style: styles.sectionTitle }, section.title),
          ...section.fields
            .filter((field) => {
              if (field.conditionalOn) {
                return data[field.conditionalOn.field] === field.conditionalOn.value;
              }
              return true;
            })
            .map((field, fi) =>
              React.createElement(View, { key: fi, style: styles.fieldRow },
                React.createElement(Text, { style: styles.fieldLabel }, field.label),
                React.createElement(Text, { style: styles.fieldValue },
                  formatValue(data[field.name])
                ),
              )
            )
        )
      ),
      React.createElement(Text, { style: styles.footer },
        `Generated by I Tatti Profile Portal — ${new Date().toISOString().split('T')[0]}`
      ),
    )
  );
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

export async function generateFormPdf(
  formDef: FormDef,
  data: Record<string, unknown>
): Promise<Buffer> {
  const element = React.createElement(FormDocument, { formDef, data }) as any;
  const stream = await ReactPDF.renderToStream(element);

  const chunks: Buffer[] = [];
  for await (const chunk of stream) {
    chunks.push(Buffer.from(chunk));
  }
  return Buffer.concat(chunks);
}
